### ISSUE TITLE
approach to enable all optimization

### ISSUE THREAD

**Issue by Mon-ius** [benwis/customs#1]
If that's possible to have all possible optimization enable together,

e.g.

1. mold
2. cranelift
3. paralle build
4. nightly build

if so, what's the best practice config in `.cargo/config.toml`

```toml
[unstable]
codegen-backend = true
[profile.server-dev]
codegen-backend = "cranelift"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold", "-Z", "threads=8", "-Z" , "codegen-backend=cranelift"]
```

Will above config fine to works for all?
